### ISSUE TITLE
uli - Add copy to clipboard support for Linux

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#13]
Add copy to clipboard for support for Linux to the **uli** addon. This should be possible with `xsel` or `xclip`. 
See this SuperUser question for helpful code snippets:
[What's like OSX's pbcopy for Linux](https://superuser.com/questions/288320/whats-like-osxs-pbcopy-for-linux)

**Comment by achekulaev** [comment]
Looking to contribute @frederickjh ? :)
Seems like an easy change to add couple of 
```bash
if (which xclip >/dev/null 2>&1); then
   ...
fi
``` 

if you have Linux and can test it.

**Comment by frederickjh** [comment]
May do. Did not have time then, but wanted to add it as it looked like a easy task that someone new to the project could code if I didn't get to it first.
