### ISSUE TITLE
Why does `uli` go to a HTTPS URL?

### ISSUE THREAD

**Issue by opdavies** [docksal/addons#18]
Why does `fin uli` go to a HTTPS URL if the Docksal domain is HTTP?

AFAIK there isn't a way to set a Docksal domain to HTTPS, so it should be HTTP? Or if a domain can be set to HTTPS then it should use HTTP when appropriate?

**Comment by opdavies** [comment]
It's a small change to remove the `sed` in `.docksal/addons/uli/uli`, but it seems like something that was added intentionally rather than a typo or something?

```diff
- uli=$(fin drush uli "$@" 2>&1 | sed "s/default/$VIRTUAL_HOST/" | sed "s/http\:/https:/")
+ uli=$(fin drush uli "$@" 2>&1 | sed "s/default/$VIRTUAL_HOST/")
```

**Comment by achekulaev** [comment]
HTTPS is the Web standard now and most of sites I was developing had HTTPS enabled or even enforced. Does it cause any issues?

**Comment by opdavies** [comment]
Certainly yes for non-local sites, but I believe all of my Docksal based sites are HTTP only - e.g. `http://drupaltest.docksal`.

For this site, if I run `fin uli` the generated one-time login link is `https://drupaltest.docksal/user/reset/1/1529521641/aSOqFe7kPrSQHFHeTkk2gMsNViL86NIOf_1O5OVsgr0/login` (note the HTTPS protocol).

If I click this link and open it in Chrome, I get a "Your connection is not private" error which I can get around by using `http://` rather than `https://` in the URL.

<img width="1392" alt="screen shot 2018-06-20 at 20 07 31" src="https://user-images.githubusercontent.com/339813/41679388-f532c732-74c5-11e8-8f65-d15430d6a673.png">

**Comment by achekulaev** [comment]
Yes you do get it, it is an expected behavior in this case.
If it bothers you you could publish PR to this addon for an option to generate http link e.g. 

```
fin uli --http
```

**Comment by opdavies** [comment]
As the domains are HTTP, I'd suggest making the `uli` link HTTP by default and adding a `--https` option to make it HTTPS?

I think the ideal scenario would be to enable a site to be HTTPS in the vhost configuration using a command like `fin secure` which sets an environment variable similar to Laravel Valet, and have the uli addon generate the correct link based on the setting?

**Comment by achekulaev** [comment]
@opdavies sounds reasonable to me

**Comment by opdavies** [comment]
Awesome. I'll submit a PR.
