### ISSUE TITLE
solr not accessable outside container

### ISSUE THREAD

**Issue by ChristianAdamski** [docksal/addons#21]
Hey,

thanks for all the work.

I installed the solr addon. It claims to be reachable by solr.{VIRTUAL_HOST} but it is not. Instead I see the Drupal page. Within the container, or more specifically within the Search API config, I can set http://solr:8983/solr" and that does work. So solr is there, but not accessible from the outside.

**Comment by achekulaev** [comment]
@ChristianAdamski if you uninstall and re-install addon it should function as you expected.

**Comment by ChristianAdamski** [comment]
Thanks, it works as expected now
