### ISSUE TITLE
Mailhog not reachable outside container

### ISSUE THREAD

**Issue by ChristianAdamski** [docksal/addons#25]
Similar to #21, mail.{VIRTUAL_HOST}.docksal does only redirect to the Drupal page.

**Comment by ChristianAdamski** [comment]
Similar to #21, exchanging the docksal.yml with 

mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail

Makes it reachable.

**Comment by achekulaev** [comment]
Addons is a community project. PRs are welcome.
