### ISSUE TITLE
Add http protocol link for uli addon

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#29]
With this change:
https://github.com/docksal/addons/blame/68e827c3d78dab5e4e26ee349bfd9651379c7558/uli/uli#L12
https://github.com/docksal/addons/blob/597705c2c6c7f924fb7cf22130c7791d62c7760a/uli/uli#L12
The protocol was changed from http to https. Are that many people using certificates on their local development environments to make this change?

I find that when I click the link in in the terminal provided by the uli addon, I always have to change the protocol in the browser from **https** to **http** for it to work. I realize that using an encrypted connection for a login is the secure thing to do but not really needed for local development environments.

Could the code be restructured so that we have both a **https** and a **http** protocol link for the User Login?

Thanks for considering this!
Frederick

**Comment by frederickjh** [comment]
I would be willing to work on coding this, just let me know if this is acceptable.

**Comment by lmakarov** [comment]
@frederickjh there is no permission required to work on an open source project and submit a PR for review :) So, yes, go for it!

**Comment by lmakarov** [comment]
> Could the code be restructured so that we have both a https and a http protocol link for the User Login?

That should be fine.

**Comment by frederickjh** [comment]
Thanks @lmakarov !
I took another look at the code. It would be easy to implement what I have suggested, however the question is then which url to copy to the clipboards in the following code. It would be strange for the user for it to presented both urls in the terminal but only copy one to the clipboard and then which one should be copied?

I am wondering if this should be split into two addons in one. `uli` for the http url and `ulis` for the https url.

What do you think? Is it possible to have two commands in one addons? Or would it be a better idea to use a command line option for one?
Say `uli -s` for the https url?

I would be happy for any input. Coding this should not be hard, deciding the best way to do so for the user interface is the bigger challenge.

**Comment by shelane** [comment]
I like the idea of the -s option. IMHO

There is also an open issue on being able to use a drush alias with the command. Would you be able to look at that one too?

**Comment by lmakarov** [comment]
@frederickjh a single addon with an option (`uli -s`) sounds like the best option.

> There is also an open issue on being able to use a drush alias with the command.

@shelane which ticker are you referring to?

**Comment by shelane** [comment]
Sorry, I was on my iPad earlier, which is never as efficient. I'm referring to #26.

**Comment by frederickjh** [comment]
@lmakarov On the way to work I also had the idea that we could do both the option and the second script. If I add the option to the current script and code it to by default output the non-secure http url, I can then make a second small bash script called `ulis` that runs the `uli` script with the `-s` option and we get the best of both worlds.

**Comment by frederickjh** [comment]
Now after taking #26 into consideration, if we plan to handle command line options for `drush uli`  command in this addon, using a command line options for the uli addon will make the code a bit more complicated if both have command line options. I need to think about how best to implement this.
