### ISSUE TITLE
[Addon Developer Support Request] - Are variables in ~/.docksal/docksal.env available to addons?

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#34]
Hi!
I was wondering if variables in `$HOME/.docksal/docksal.env` are available to addons?

My use case is this: the **uli** addon now defaults to outputing the link as http the **-s** option needs to be given to get a SSL link using https. 

I would like to add an variable that would allow a user to set this so that it defaults to SSL links for the uli addon command.

I think it would be good then to also add another option, maybe **-u**, that would allow a user to choose to get the link as an **u**nsecure http link if this variable was set.

Let me know your thoughts on this and a good variable name for `$HOME/.docksal/docksal.env`
Thanks for your time and help!
Frederick

**Comment by achekulaev** [comment]
@frederickjh just do `. $PROJECT_ROOT/.docksal/docksal.env` in your addon to source in the variables

**Comment by frederickjh** [comment]
Thanks @achekulaev. 

Is **DOCKSAL_ADDON_ULI_SSL** a good name for the variable that if set to true would always return links with https?

**Comment by achekulaev** [comment]
I would call it `DOCKSAL_ADDON_ULI_USE_HTTPS` to just be more clear
