### ISSUE TITLE
Enhancement - Add variable to uli addon to allow SSL link by default

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#36]
Since defaulting to non-ssl links and adding the **-s** option to the uli addon and now having switched to using SSL certificates on my development sites I find myself forgetting to type the **-s** option each time I use the `fin uli` command.

This issue is an enhancement that would add a variable **DOCKSAL_ADDON_ULI_USE_HTTPS** that could be placed in `$HOME/.docksal/docksal.env`  or a project's `docksal-local.env` and set to **1** to default to SSL links.

However to make it still possible to get non-SSL links I propose adding a **-i** option (for **i**nsecure) to the addon. The **-s** and **-i** options will take precedence over the **DOCKSAL_ADDON_ULI_USE_HTTPS** variable setting.

**Comment by achekulaev** [comment]
But the correct word is **i**nsecure :)

**Comment by frederickjh** [comment]
OK, then the switch can be **-i** instead of **-u**.
