### ISSUE TITLE
Standarize domain names for addons to not use a subdomain of a project domain name

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#56]
Some addons use a subdomain of the `${VIRTUAL_HOST}`, but if you are using a LetsEncrypt Wildcard domain for your Docksal projects it is only good for one level of subdomain not two.

ie. LetsEncrypt wildcard domain certificate is for ***.dev.example.com**, so it would be valid for the projects listed below but not for Docksal addons that use a domain name that is a subdomain of a subdomain of dev.example.com

Projects are at:
* project.dev.example.com
* project2.dev.example.com
etc.

Not valid with wildcard certificate:
* **webmail**.project.dev.example.com
* **adminer**.project.dev.example.com
etc.

If a dash is used instead of a period a subdomain is used that is valid for the wildcard certificate.

Valid with wildcard certificate:
* **webmail-project**.dev.example.com
* **adminer-project**.dev.example.com

I believe I suggested using a dash instead of a period for the IDE and it is configured so.
* ide-project.dev.example.com
See [Enabling IDE](https://docs.docksal.io/tools/ide/#enabling-ide) in the documentation.

I know that the following addons need this change:
* ~~Adminer~~ Pull request submitted.
* ~~Mailhog~~ Already in code.
Others may need it too but I do not use all of them.

**Comment by frederickjh** [comment]
@achekulaev I take it that you checked through the other addons or know that they have switched to use a prefix on the project name as their subdomain name instead of using a subdomain name of the project subdomain name, since you closed this.

**Comment by achekulaev** [comment]
@frederickjh well I see the addons you mentioned are covered. I have not checked through other addons. (and frankly have no intention of doing so, this is kind of community-supported repo)

**Comment by frederickjh** [comment]
OK @achekulaev I will take a look and see what I can find.

**Comment by frederickjh** [comment]
The **pma** addon is the only other addon that I could find using a subdomain of the project subdomain name. I will see what I can do about submitting a pull request for it. The rest of the addons either do not use a web interface or have been changed to use a prefix to the project name.
